### ISSUE TITLE
vcfdo polarize

### ISSUE THREAD

**Issue by nickbrazeau** [IDEELResearch/vcfdo#1]
This function writes out missing sites with too many periods (eg includes format periods). For example, in the format of GT:AD:DP it writes out "./.:.:." instead of just "." (for haploid). 

Per vcf 4.2 specs https://samtools.github.io/hts-specs/VCFv4.2.pdf
"If a call cannot be made for a sample at a given locus, ‘.’ should be specified for each missing allele in the GT field (for example ‘./.’ for a diploid genotype and ‘.’ for haploid genotype). The meanings of the separators are as follows (see the PS field below for more details on incorporating phasing information into the genotypes)"

The extra periods cause conflicts with the vcfR package and missing data is not correctly imported.

I can fix this import issue in R but just wanted to mention this in case it was causing conflicts elsewhere. Thanks again for a great package!

**Comment by andrewparkermorgan** [comment]
I think the VCF spec calls for the missing-data code (`.`) in each `FORMAT` field for which data is missing.  See section 1.6.2 (https://samtools.github.io/hts-specs/VCFv4.3.pdf). So `./.:.:.` is valid if all of `GT`, `AD` and `DP` are missing. Strange that `AD` and `DP` would be missing rather than reported as zero, though.

In any case the `polarize` subcommand only touches the `INFO` fields and passes genotype columns through without any _intentional_ modification. All the VCF parsing is done by `cyvcf2` which itself is a thin wrapper around `htslib`, so I wouldn't expect anything to happen to the genotype columns that wouldn't happen if you just stream through the file with `bcftools view`.

Can you show a snippet of a VCF that is giving you problems?

**Comment by nickbrazeau** [comment]
Hey Andrew, 

The culprit vcf was one of the mip vcfs. I understand where the issue is now (related to how we are writing it out) and see where `cyvcf` is just touching the code. My mistake for blaming `polarize`. I am closing this as a result. Thanks!
